### ISSUE TITLE
Cannot find GPU

### ISSUE THREAD

**Issue by euronay** [Krutonium/BetterFanController#10]
Hi

I'm looking for a project to hack on for Hacktoberfest, and this looks interesting!  However, I tried to run the app and was met with the following exception:
```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/drm/card1/device/hwmon/hwmon1/pwm1_enable'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at BetterFanController.Program.GPU.get_FanState() in /home/james/Projects/BetterFanController/BetterFanController/Program.cs:line 133
   at BetterFanController.Program.Main(String[] args) in /home/james/Projects/BetterFanController/BetterFanController/Program.cs:line 57
```
This line in `FanState` is trying to get the `hwmonX` folder with the GPU number, which in my case is 1:
```c#
string temp = File.ReadAllText(path + "/device/hwmon/hwmon" + gpuNumber + "/pwm1_enable");
```

It appears that I only have a `hwmon3` in my directory:
![image](https://user-images.githubusercontent.com/3864985/95574995-d5aec300-0a25-11eb-9bca-e2663309883c.png)

If I manually change my GPU number to 3, the program starts to work just fine!

I'm happy to have a look at this and fix it, but I was wondering where the number in the `hwmonX` folder comes from. What does your folder look like? Would a possible solution be to iterate the parent directory to find the first `hwmonX` folder?

Once I've got it working, I'd love to pick up some of the other issues.

Cheers

James

**Comment by Krutonium** [comment]
On my system, I've only ever seen `hwmon[int]` have the same value as the card number, and I have two cards so that seemed like a safe assumption. I guess I was wrong!

Off Topic, what Icon theme are you using?

**Comment by euronay** [comment]
Weird!

It's just the default icon theme in Ubuntu 20.04 😊
