### ISSUE TITLE
When running as a service it never updates the fans

### ISSUE THREAD

**Issue by Krutonium** [Krutonium/BetterFanController#14]
Specifically, if I run it within Rider or Directly it will print log output as well as actually adjusting the fans. Once it's running in systemd however, there is no logging and it never actually adjusts the fans.

**Comment by euronay** [comment]
Hmm. Are you seeing anything at all when you run 
```
​sudo journalctl -u betterfancontroller
```
?

**Comment by Krutonium** [comment]
Nope

(At the time I wrote this it never got past the "starting" phase)

**Comment by Krutonium** [comment]
```
sudo systemctl status betterfancontroller
[sudo] password for krutonium: 
● betterfancontroller.service - Better Fan Controller
     Loaded: loaded (/etc/systemd/system/betterfancontroller.service; disabled;>
     Active: inactive (dead)
 ✘ krutonium@gamingpc  ~  sudo systemctl start betterfancontroller
Job for betterfancontroller.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status betterfancontroller.service" and "journalctl -xe" for details.
 ✘ krutonium@gamingpc  ~  sudo systemctl status betterfancontroller
● betterfancontroller.service - Better Fan Controller
     Loaded: loaded (/etc/systemd/system/betterfancontroller.service; disabled>
     Active: failed (Result: core-dump) since Thu 2020-10-15 19:38:02 EDT; 9s >
    Process: 3486 ExecStart=/usr/sbin/BetterFanController (code=dumped, signal>
   Main PID: 3486 (code=dumped, signal=ABRT)
Oct 15 19:38:01 gamingpc BetterFanController[3486]:    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
Oct 15 19:38:01 gamingpc BetterFanController[3486]:    at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
Oct 15 19:38:01 gamingpc BetterFanController[3486]:    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
Oct 15 19:38:01 gamingpc BetterFanController[3486]:    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
Oct 15 19:38:01 gamingpc BetterFanController[3486]:    at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
Oct 15 19:38:01 gamingpc BetterFanController[3486]:    at Microsoft.Extensions.Hosting.HostBuilder.Build()
Oct 15 19:38:01 gamingpc BetterFanController[3486]:    at BetterFanController.Program.Main(String[] args)
Oct 15 19:38:02 gamingpc systemd[1]: betterfancontroller.service: Main process exited, code=dumped, status=6/ABRT
Oct 15 19:38:02 gamingpc systemd[1]: betterfancontroller.service: Failed with result 'core-dump'.
Oct 15 19:38:02 gamingpc systemd[1]: Failed to start Better Fan Controller.
```

**Comment by euronay** [comment]
OK so it is at least trying to start! Unfortunately I can only see half a stack trace. Can you try running `sudo /usr/sbin/BetterFanController` directly from the shell and post the output?

**Comment by Krutonium** [comment]
It starts fine.
```
krutonium@gamingpc  ~  sudo /usr/sbin/BetterFanController
info: BetterFanController.FanController[0]
      Found Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 at path /sys/class/drm/card0.
info: BetterFanController.FanController[0]
      Indexed GPUs
info: BetterFanController.FanController[0]
      Please note that the first 5 lines of this log are wrong while the application calibrates itself.
info: BetterFanController.FanController[0]
      Set GPU RX 5600 XT at 29c (Average temp of 1000c) to a PWM Speed of 73
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/krutonium
info: BetterFanController.FanController[0]
      Set GPU RX 5600 XT at 29c (Average temp of 805c) to a PWM Speed of 255
info: BetterFanController.FanController[0]
      Set GPU RX 5600 XT at 29c (Average temp of 611c) to a PWM Speed of 255
info: BetterFanController.FanController[0]
      Set GPU RX 5600 XT at 29c (Average temp of 417c) to a PWM Speed of 255
info: BetterFanController.FanController[0]
      Set GPU RX 5600 XT at 29c (Average temp of 223c) to a PWM Speed of 255
info: BetterFanController.FanController[0]
      Set GPU RX 5600 XT at 29c (Average temp of 29c) to a PWM Speed of 255
info: BetterFanController.FanController[0]
      Set GPU RX 5600 XT at 29c (Average temp of 29c) to a PWM Speed of 91
info: BetterFanController.FanController[0]
      Set GPU RX 5600 XT at 29c (Average temp of 29c) to a PWM Speed of 73
info: BetterFanController.FanController[0]
      Set GPU RX 5600 XT at 29c (Average temp of 29c) to a PWM Speed of 73
```

**Comment by Krutonium** [comment]
```
Oct 16 04:50:37 gamingpc systemd[1]: Starting Better Fan Controller...
Oct 16 04:51:01 gamingpc BetterFanController[3105]: Unhandled exception. System.IO.IOException: Invalid argument
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notif>
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.StartRaisingEvents()
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at Microsoft.Extensions.Hosting.HostBuilder.Build()
Oct 16 04:51:01 gamingpc BetterFanController[3105]:    at BetterFanController.Program.Main(String[] args)
Oct 16 04:51:02 gamingpc systemd[1]: betterfancontroller.service: Main process exited, code=dumped, status=6/ABRT
Oct 16 04:51:02 gamingpc systemd[1]: betterfancontroller.service: Failed with result 'core-dump'.
Oct 16 04:51:02 gamingpc systemd[1]: Failed to start Better Fan Controller.

```

The full dump, didn't realize I'd actually lost the top.

**Comment by euronay** [comment]
Welp. I wonder if it's permissions or something?

I'm not that familiar with Arch, can you see what permissions you have on the bin? 

Here's the output of `getfacl /usr/sbin/BetterFanController` on my machine
```
# file: usr/sbin/BetterFanController
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
```

Seems weird that you can run it from the console - that definitely hints at permissions to me. I don't know what user systemd uses.

**Comment by Krutonium** [comment]
iirc If you don't specify it runs it as root, let me check permissions...

**Comment by Krutonium** [comment]
```
getfacl /usr/sbin/BetterFanController 
getfacl: Removing leading '/' from absolute path names
# file: usr/sbin/BetterFanController
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
```

**Comment by euronay** [comment]
OK I've made an Arch VM on my machine and I'm seeing the same as you now. So at least it's reproducible! 

I'll have a play around and see if I can narrow down the problem 🤔

**Comment by Krutonium** [comment]
I've tried going so far as to changing what user the application runs under, both as root and another account that may as well be root have the issue.

Thanks for sticking around to help sort this, by the way, I appreciate it.
